version: '3.8'

name: old-market-balance

services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: otreedb
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lee
    volumes:
      - db-postgres:/var/lib/postgresql/data

  otree:
    container_name: otree
    build: .
    environment:
      DATABASE_URL: postgresql://otreedb:postgres@postgres/lee
      OTREE_PRODUCTION: 1
      OTREE_AUTH_LEVEL: STUDY
      OTREE_ADMIN_USERNAME: admin_lee
      OTREE_ADMIN_PASSWORD: 151418
    ports:
      - "80:8000"

volumes:
  db-postgres: